server:
   port: 9997

spring:
   profiles:
      active: local
   
   devtools:
      livereload:
         enabled: true
      restart:
         enabled: true

#   config:
#      activate:
#         on-profile: local

   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://223.130.134.136:3306/DMS02?serverTimezone=UTC&characterEncoding=UTF-8
      username: bdwide
      password: Bdwide365!@

      #운영DB
#         url: jdbc:mysql://localhost:3306/DMS02?serverTimezone=UTC&characterEncoding=UTF-8
#         username: bdwide
#         password: Bdwide365!@

mybatis:
   mapper-locations: /mapper/**/*.xml
   configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true

#log
logging:
   file: 
      path: logs/