#spring
spring:
   profiles:
      active: solarmy
   
   devtools:
      restart:
         enabled: true

#   mvc:
#      servlet:
#         path: /swagger-ui.html

#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /

#mybatis
mybatis:
   mapper-locations: /mapper/**/*.xml
   configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true

#log
logging:
   file: 
      path: logs/

---
#솔라미
spring:
   config.activate.on-profile: solarmy
   datasource:
    #로컬DB
#      url: jdbc:mysql://223.130.134.136:3306/DMS02?serverTimezone=UTC&characterEncoding=UTF-8
#      username: bdwide
#      password: Bdwide365!@

    #운영DB
      url: jdbc:mysql://localhost:3306/DMS02?serverTimezone=UTC&characterEncoding=UTF-8
      username: bdwide
      password: Bdwide365!@

server: 
   port: 9997